---
title: "CCC Activities across the Casco and Home Claim Management Lifecycle (A Business Case Candidate)"
author: "János Poór"
date: 'April 24, 2019'
output: rmdformats::readthedown
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, message = FALSE, echo = TRUE, include = FALSE}
library(config)
library(dplyr)
library(ggplot2)
library(purrr)
library(lubridate)
library(gridExtra)
library(tidyr)
library(scales)
library(stringr)
```


```{r, include=FALSE}
# Data Extraction #######################################################################

# Set JAVA_HOME, set max. memory, and load rJava library
Sys.setenv(JAVA_HOME = "C:\\Program Files\\Java\\jre1.8.0_171")
options(java.parameters = "-Xmx2g")
library(rJava)

# Output Java version
.jinit()
print(.jcall("java/lang/System", "S", "getProperty", "java.version"))

# Load RJDBC library
library(RJDBC)

# Get credentials
datamnr <-
  config::get("datamnr", file = "C:\\Users\\PoorJ\\Projects\\config.yml")

# Create connection driver
jdbcDriver <-
  JDBC(driverClass = "oracle.jdbc.OracleDriver", classPath = "C:\\Users\\PoorJ\\Desktop\\ojdbc7.jar")

# Open connection: kontakt
jdbcConnection <-
  dbConnect(
    jdbcDriver,
    url = datamnr$server,
    user = datamnr$uid,
    password = datamnr$pwd
  )

# Fetch Home data
query_branches <- "SELECT * FROM T_CLAIMS_HOME_DISTINCT"
t_home_branches <- dbGetQuery(jdbcConnection, query_branches)

query_branches_paid <- "SELECT * FROM T_CLAIMS_HOME_DISTINCT_PAID"
t_home_branches_paid <- dbGetQuery(jdbcConnection, query_branches_paid)

query_cutpoints <- "SELECT * FROM T_CLAIMS_HOME_MILESTONES"
t_home_cutpoints <- dbGetQuery(jdbcConnection, query_cutpoints)

query_eventlog <-
"SELECT * FROM T_CLAIMS_HOME_KONTAKT_EVENTLOG"
t_home_eventlog <- dbGetQuery(jdbcConnection, query_eventlog)



# Fetch Casco data
query_branches <- "SELECT * FROM T_CLAIMS_MILESTONES"
t_casco_branches <- dbGetQuery(jdbcConnection, query_branches)

query_cutpoints <- "SELECT * FROM T_CLAIMS_MILESTONES_CLEANED"
t_casco_cutpoints <- dbGetQuery(jdbcConnection, query_cutpoints)

query_eventlog <-
"SELECT * FROM T_CLAIMS_PA_OUTPUT_CCC_OKK a WHERE milestones IS NOT NULL
AND EXISTS (SELECT 1 FROM T_CLAIMS_MILESTONES_CLEANED b WHERE a.case_id = b.case_id)"
t_casco_eventlog <- dbGetQuery(jdbcConnection, query_eventlog)


# Close db connection: kontakt
dbDisconnect(jdbcConnection)


# Transform data
t_home_eventlog <- t_home_eventlog %>% mutate_at(vars(EVENT_END), ymd_hms)
t_home_branches <- t_home_branches %>% mutate_at(vars(F_KARIDO, F_KARBEIDO, F_UTALAS_FIRST), ymd_hms)
t_home_branches_paid <- t_home_branches_paid %>% mutate_at(vars(F_KARIDO, F_KARBEIDO, F_UTALAS_FIRST), ymd_hms)
t_casco_eventlog <- t_casco_eventlog %>% mutate_at(vars(EVENT_END), ymd_hms)
t_casco_branches <- t_casco_branches %>% mutate_at(vars(CLAIM_REPORT_DATE, CLAIM_DECISION_DATE, CLAIM_CLOSE_DATE), ymd_hms)
```

# Contact Center Interactions 

```{r, message=FALSE}
t_home_eventlog %>% 
  filter(ACTIVITY_TYPE == "KONTAKT CCC") %>% 
  group_by(ACTIVITY_CHANNEL) %>% 
  summarize(COUNT = length(CASE_ID),
            COUNT_DISTINCT = length(unique(CASE_ID)),
            INT_PER_CASE = length(CASE_ID)/length(unique(CASE_ID)))
```

```{r, message=FALSE}
t_casco_eventlog %>% 
  filter(ACTIVITY_TYPE == "KONTAKT CCC") %>% 
  group_by(ACTIVITY_CHANNEL) %>% 
  summarize(COUNT = length(CASE_ID),
            COUNT_DISTINCT = length(unique(CASE_ID)),
            INT_PER_CASE = length(CASE_ID)/length(unique(CASE_ID)))
```

```{r, message=FALSE}
# Casco lifecycles ######################################################################
# Define lifecycle cutpoints
t_casco_cutpoints_long <- t_casco_cutpoints %>%
  filter(REPORT_LOWERBOUND < as.Date("2018-07-01")) %>%
  mutate_at(vars(REPORT_LOWERBOUND:CLOSE_UPPERBOUND), ymd_hms) %>%
  select(-DECISION_LOWERBOUND, -DECISION_UPPERBOUND) %>% 
  tidyr::gather(-CASE_ID, -CASE_TYPE, -MILESTONES, key = CUTPOINT, value = CUTDATE) %>%
  arrange(CASE_ID, CUTPOINT) %>% 
  filter(!is.na(CUTDATE))


# Org specific event seqs
t_casco_events_ccc <- t_casco_eventlog %>%
  filter(
        CASE_ID %in% t_casco_cutpoints_long$CASE_ID
        & ACTIVITY_TYPE == "KONTAKT CCC"
        #& ACTIVITY_CHANNEL == "CALL"
        ) %>%
  select(CASE_ID, CASE_TYPE, MILESTONES, EVENT_END, ACTIVITY_CHANNEL)


t_casco_events_okk <- t_casco_eventlog %>%
  filter(
        CASE_ID %in% t_casco_cutpoints_long$CASE_ID &
        ACTIVITY_TYPE == "KONTAKT OKK") %>%
  select(CASE_ID, CASE_TYPE, MILESTONES, EVENT_END)


# Define Func to Compute Bins
create_bins_casco_2 <- function(df, case_id) {
  t_cutpoints_long_filtered <- t_casco_cutpoints_long[t_casco_cutpoints_long$CASE_ID == case_id, ] %>% arrange(CUTDATE)
  as.character(cut(df$EVENT_END,
    breaks = c(t_cutpoints_long_filtered$CUTDATE, Inf),
    labels = t_cutpoints_long_filtered$CUTPOINT
  ))
}


# Genereate bins
by_case_id_casco_ccc <- t_casco_events_ccc %>%
  select(-MILESTONES) %>% 
  group_by(CASE_ID, CASE_TYPE, ACTIVITY_CHANNEL) %>%
  nest() %>%
  mutate(BINS = map2(data, .$CASE_ID, ~create_bins_casco_2(df = .x, case_id = .y)))
```


```{r, message=FALSE}
# Home lifecycles ######################################################################
# Define lifecycle cutpoints
t_home_cutpoints_long <- t_home_cutpoints %>%
  #filter(REPORT_LOWERBOUND < as.Date("2018-07-01")) %>%
  filter(REPORT_LOWERBOUND != CLOSE_LOWERBOUND) %>% 
  mutate_at(vars(REPORT_LOWERBOUND:CLOSE_UPPERBOUND), ymd_hms) %>%
  #select(-DECISION_LOWERBOUND, -DECISION_UPPERBOUND) %>% 
  tidyr::gather(-CASE_ID, -CASE_TYPE, -PRODUCT_CODE, key = CUTPOINT, value = CUTDATE) %>%
  arrange(CASE_ID, CUTPOINT) %>% 
  filter(!is.na(CUTDATE))


# Org specific event seqs
t_home_events_ccc <- t_home_eventlog %>%
  filter(
        CASE_ID %in% t_home_cutpoints_long$CASE_ID
        & ACTIVITY_TYPE == "KONTAKT CCC"
        #& ACTIVITY_CHANNEL == "CALL"
        ) %>%
  select(CASE_ID, CASE_TYPE, EVENT_END, ACTIVITY_CHANNEL)


t_home_events_okk <- t_home_eventlog %>%
  filter(
        CASE_ID %in% t_home_cutpoints_long$CASE_ID &
        ACTIVITY_TYPE == "KONTAKT OKK") %>%
  select(CASE_ID, CASE_TYPE, EVENT_END)


# Define Func to Compute Bins
create_bins_home_2 <- function(df, case_id) {
  t_cutpoints_long_filtered <- t_home_cutpoints_long[t_home_cutpoints_long$CASE_ID == case_id, ] %>% arrange(CUTDATE)
  as.character(cut(df$EVENT_END,
    breaks = c(t_cutpoints_long_filtered$CUTDATE, Inf),
    labels = t_cutpoints_long_filtered$CUTPOINT
  ))
}


# Genereate bins
by_case_id_home_ccc <- t_home_events_ccc %>%
  #select(-MILESTONES) %>% 
  group_by(CASE_ID, CASE_TYPE, ACTIVITY_CHANNEL) %>%
  nest() %>%
  mutate(BINS = map2(data, .$CASE_ID, ~create_bins_home_2(df = .x, case_id = .y)))
```

```{r, message=FALSE}
# Merge
casco <- by_case_id_casco_ccc %>% select(CASE_ID, CASE_TYPE, ACTIVITY_CHANNEL, data, BINS) %>% unnest() %>% 
  mutate(
    PERIOD = case_when(
      is.na(BINS) ~ '1_BEFORE_REPORT',
      BINS == 'REPORT_LOWERBOUND' ~ '2_ON_REPORT',
      BINS == 'REPORT_UPPERBOUND' ~ '3_BETWEEN_REPORT_CLOSE',
      BINS == 'CLOSE_LOWERBOUND' ~ '4_ON_CLOSE',
      BINS == 'CLOSE_UPPERBOUND' ~ '5_AFTER_CLOSE'
    ),
    PRODUCT_LINE = 'CASCO',
    CASE_TYPE = case_when(
      CASE_TYPE == 'ALTERNATIVE' ~ 'ALTER/SIMPLE',
      TRUE ~ CASE_TYPE
    )
  )

home <- by_case_id_home_ccc %>% select(CASE_ID, CASE_TYPE, ACTIVITY_CHANNEL, data, BINS) %>% unnest() %>% 
  mutate(
    PERIOD = case_when(
      is.na(BINS) ~ '1_BEFORE_REPORT',
      BINS == 'REPORT_LOWERBOUND' ~ '2_ON_REPORT',
      BINS == 'REPORT_UPPERBOUND' ~ '3_BETWEEN_REPORT_CLOSE',
      BINS == 'CLOSE_LOWERBOUND' ~ '4_ON_CLOSE',
      BINS == 'CLOSE_UPPERBOUND' ~ '5_AFTER_CLOSE'
    ),
    PRODUCT_LINE = 'HOME',
    CASE_TYPE = case_when(
      CASE_TYPE == 'Simple' ~ 'ALTER/SIMPLE',
      CASE_TYPE == 'Standard' ~ 'STANDARD',
      CASE_TYPE == 'Exception' ~ 'EXCEPTION'
    )
  )

t_lifecycles <- bind_rows(casco, home)

# Write to local storage
write.csv(t_lifecycles,
          here::here("Data", "t_lifecycles_home_casco.csv"),
          row.names = FALSE)
```

# Comparison of Incoming Calls across the Claim Management Lifecycle

```{r, message=FALSE}
# Load from local cache
t_lifecycles <- read.csv(here::here("Data", "t_lifecycles_home_casco.csv"), stringsAsFactors = FALSE)

# Graph
t_lifecycles %>% 
group_by(PRODUCT_LINE, PERIOD) %>%
  summarize(N_OF_CALLS = n()) %>%
  ungroup() %>%
  group_by(PRODUCT_LINE) %>% 
  mutate(RATIO = N_OF_CALLS/sum(N_OF_CALLS)) %>% 
  ungroup() %>% 
  ggplot(aes(x = PERIOD, y = RATIO)) +
    geom_bar(stat = "identity") +
    scale_y_continuous(labels = percent) +
    theme(axis.text.x = element_text(angle = 90)) +
    facet_grid(PRODUCT_LINE~.) + 
    labs(
        x = "Lifecycle",
        y = "# of Calls",
        title = "Number of Calls across Claim File Lifecycle"
      )
```


# Comparison of Incomoing Calls across the Claim Management Lifecycle by Process Branch

```{r, message=FALSE}
# Graph
t_lifecycles %>% 
group_by(PRODUCT_LINE, PERIOD, CASE_TYPE) %>%
  summarize(N_OF_CALLS = n()) %>%
  ungroup() %>%
  group_by(PRODUCT_LINE, CASE_TYPE) %>% 
  mutate(RATIO = N_OF_CALLS/sum(N_OF_CALLS)) %>% 
  ungroup() %>% 
  ggplot(aes(x = PERIOD, y = RATIO)) +
    geom_bar(stat = "identity") +
    scale_y_continuous(labels = percent) +
    theme(axis.text.x = element_text(angle = 90)) +
    facet_grid(PRODUCT_LINE~CASE_TYPE) + 
    labs(
        x = "Lifecycle",
        y = "# of Calls",
        title = "Number of Calls across Claim File Lifecycle"
      )
```